geoplatform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'geoplatform') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'geoplatform') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'geoplatform') }}"
      schema: dbt_geoplatform
      threads: 4
  
  # Send OpenLineage events to DataHub when dbt runs
  openlineage:
    url: http://datahub-gms:8080
    namespace: geoplatform.dbt
